### ISSUE TITLE
After Export, The archive file is corrupted !!?

### ISSUE THREAD

**Issue by RoroRoze** [prathercc/discrub-ext#100]
After waiting for Hours to export, File Size 20GB
When unzip the file with WinRAR it gives two Error "The archive is corrupt" & "No files to extract"
I tried again on another channel, but got the same errors 

I'm using the extension on Opera Browser
Windows 10
WinRAR 5.70 (64-bit)

![image](https://github.com/prathercc/discrub-ext/assets/65495906/a2da7fac-a296-488e-8a90-4dc74bf8882a)

**Comment by RoroRoze** [comment]
It is Working ✅
It Was WinRAR problem, When i used 7zip to extract the archive, everything worked perfectly.
Thank you soo much for the amazing Extension.

**Comment by prathercc** [comment]
I'm glad you've got the issue resolved! Thanks for the kind words <3
