### ISSUE TITLE
Paging controls in exported HTML

### ISSUE THREAD

**Issue by pcolton** [prathercc/discrub-ext#104]
I may have missed it, but would be nice to add paging controls in the exported HTML (when multiple pages are exported, of course).

**Comment by prathercc** [comment]
Would this be more so that you can view the next/previous page without having to leave the browser?

**Comment by pcolton** [comment]
Right. For example, if my export has 20 pages, I would love to be able to say next page, prev page, etc., so I could continue reading without having to go back to the file system to load the next page manually.

**Comment by prathercc** [comment]
This will be included with Version 1.12.0 👍
