### ISSUE TITLE
Console Warning in Devtools

### ISSUE THREAD

**Issue by BC4Coding** [prathercc/discrub-ext#105]
While trying my first DM archive I got the following message in the Developer Tools console. Please advise

Chromium
Version 112.0.5615.49
=== === ===

Hold Up! 43455.8c79ce3e1753b38de4a4.js:23 If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.

**Comment by prathercc** [comment]
Hey there, that warning is something Discord automatically displays when opening the console, its intended to help protect people from being scammed and pasting malicious code there.
This isn't anything to worry about and is unrelated to the extension!
