### ISSUE TITLE
Feature: Only export a limited amount

### ISSUE THREAD

**Issue by Explosifbe** [prathercc/discrub-ext#109]
Would it be possible to only export x amount of messages, or the last 24 hours of messages maybe?
Or maybe even update a file with the latest content?

Cheers

**Comment by prathercc** [comment]
Right now you could use the Advanced Filtering to export starting from a specific time/time-frame, but it’s not possible to export X amount of messages at the moment.

**Comment by Explosifbe** [comment]
> Right now you could use the Advanced Filtering to export starting from a specific time/time-frame, but it’s not possible to export X amount of messages at the moment.

Oh, didn't realize that was a feature, it's perfect for what I need.
Issue can be closed
