### ISSUE TITLE
Export as separate threads

### ISSUE THREAD

**Issue by demiculus** [prathercc/discrub-ext#112]
## Problem
My channels have 200 threads. It'll be a pain to export every single one of them separately.  

## Solution

When we export the whole channel we can have a button here that folders all the threads separately

![image](https://github.com/prathercc/discrub-ext/assets/6215305/405c888f-313e-4c59-9714-4f25fc9f124c)

That way the exported content will look like this.

```
/channelName 
  channelText
  thread1
  thread2
  ...
```

**Comment by prathercc** [comment]
This will be included with Version 1.11.14 (PR #115), it should be available in the next day or so, once the Chrome store publishes the package.

When performing exports, there will be a new Separate Threads & Forum Posts toggle that can be used.
Closing this issue now, but feel free to create a new one if something else pops up, thanks!
