### ISSUE TITLE
Feature Request: Export the Whole Server 

### ISSUE THREAD

**Issue by RoroRoze** [prathercc/discrub-ext#114]
Feature Request:
It would be very convenient and time saver if we could select a server and export all the content, then the export result will be a folder for each channel and threads. The same filtering system can stay as it is.

or at leas have the option to select multiple channels at once to avoid selecting channel by channel.

Thank you...

**Comment by prathercc** [comment]
Hey there, you can currently export an entire server by selecting the server and then using the Export button.
It will list all of the channels available and allow you to select any or all of them for export.

Also, once Version 1.11.14 is deployed, you will have an additional export option available to you called Separate Threads & Forum Posts, that will ensure that each thread/forum-post is inside of a separate file.

Let me know if that answers your question or not 👍
<img width="737" alt="Screenshot 2024-07-12 at 10 40 38 AM" src="https://github.com/user-attachments/assets/ab1453d3-b54e-4fa6-ab50-ca3a09bcfc53">

**Comment by RoroRoze** [comment]
Thank you so much for the new features, both the whole server export, selecting multiple channels, and separate by threads.

But I noticed when exporting whole server or multiple channels at once we can't filter by date or user name !!
as it would be more convenient to export whole server but except messages for a specific user (e.g. my messages) and between specific date, so next time I export I will start from the last date I performed an exported...

Screenshot as Export server grey out when specifying a date:
![image](https://github.com/user-attachments/assets/e555bbfd-a007-4e15-ad71-90dc6653a591)

**Comment by prathercc** [comment]
> Thank you so much for the new features, both the whole server export, selecting multiple channels, and separate by threads.
> 
> But I noticed when exporting whole server or multiple channels at once we can't filter by date or user name !! as it would be more convenient to export whole server but except messages for a specific user (e.g. my messages) and between specific date, so next time I export I will start from the last date I performed an exported...
> 
> Screenshot as Export server grey out when specifying a date: ![image](https://private-user-images.githubusercontent.com/65495906/348552610-e555bbfd-a007-4e15-ad71-90dc6653a591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDkzMzEsIm5iZiI6MTcyMTAwOTAzMSwicGF0aCI6Ii82NTQ5NTkwNi8zNDg1NTI2MTAtZTU1NWJiZmQtYTAwNy00ZTE1LWFkNzEtOTBkYzY2NTNhNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDAyMDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YjlmZTY3ZmNhZTQzYWYwZjZiYzFiNGFjNWExNjFjMTM4NmQ3MDc5NGUzOWZjNGY2MGRiMjMwYTdiN2FjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wza0RhGuFNFM5v6FUxXsL3SoL9Y8rhSrcDBBXQFchJQ)

This should be something Discrub could support, I’ll take a look and try to get it added 👍

**Comment by prathercc** [comment]
This will be included with Version 1.11.15, available in the next day or so on the Chrome store 👍
Closing this issue but feel free to create another one if something else pops up!
