### ISSUE TITLE
Preview option without download attachments enabled, makes images not accessible.

### ISSUE THREAD

**Issue by jirafey** [prathercc/discrub-ext#116]
Just exported one of my bigger servers as HTML, is the behaviour expected? I hope that if I just enable `download attachments` then the problem will be fixed but that makes the file so much larger than it could be.

**Comment by jirafey** [comment]
![image](https://github.com/user-attachments/assets/eda39a8e-eaa5-4d7d-b65f-e5f9d3547613)
first 18 messages (sorting from the latest to the oldest)

**Comment by prathercc** [comment]
Unfortunately this is an issue on Discord's side of things 😕
A while back they decided to make media links expire, so if you are wanting to archive messages long term, it is better to ensure that media is being downloaded as part of your export.
