### ISSUE TITLE
Download images or videos from links

### ISSUE THREAD

**Issue by batubabaxx** [prathercc/discrub-ext#119]
Some people usually post images / videos by using link and discord makes preview to watch it easily without clicking, i was wondering if we can able to download them too? I mean it would be so good, i hope its possible.

**Comment by prathercc** [comment]
Tagging https://github.com/prathercc/discrub-ext/commit/90d0d2446f853c374eae6f10f3afa60abb017384 to this issue

**Comment by prathercc** [comment]
Closing this issue, embedded images/video will now be a selectable export option with Version 1.12.4.
https://github.com/prathercc/discrub-ext/releases/tag/1.12.14
