### ISSUE TITLE
JSON formatting error in donation gist broke the entire extension

### ISSUE THREAD

**Issue by jacobcxdev** [prathercc/discrub-ext#126]
See [this comment](https://gist.github.com/prathercc/2aca7928b4db1ab84eac3720ac8e8559?permalink_comment_id=5162669#gistcomment-5162669).

There should really be some error handling to prevent this kind of thing from taking down the entire extension.

**Comment by prathercc** [comment]
This was my bad 😞 It should be fixed now!
