### ISSUE TITLE
ZIP is corrupt if large (25 GB)

### ISSUE THREAD

**Issue by HSNB** [prathercc/discrub-ext#132]
ZIP will be corrupt if it's big, in my case 27 GB.
WinRAR still extracts files up to a point, then it fails.

Might have to do with the code not using 64-bit (unsigned) integers. (I haven't checked the code atm)

Another thing that would be nice if we can choose not to include video's in the media export (so only images), then it'd not get so big.

Thanks :)

**Comment by imba-pericia** [comment]
Similar errors with zip, 7za unpacked the entire archive without errors.
