### ISSUE TITLE
Support code highlighting in snippets

### ISSUE THREAD

**Issue by gmile** [prathercc/discrub-ext#143]
Right now, when the post contains code, the code highlighting is broken. Here's an example upon test export from `motion-canvas` server:

![CleanShot 2024-11-20 at 14 27 46@2x](https://github.com/user-attachments/assets/4633b5a7-e518-460f-86eb-36b9d73c6868)

It would be fantastic if the code highlighting worked for html.

**Comment by prathercc** [comment]
I’ll try to have this fixed on the next release 👍

**Comment by gmile** [comment]
One small thing somewhat related to code highlighting: perhaps the inline code, e.g. surrounded with ticks, could use one of system default monospace fonts 🤔 

![CleanShot 2024-11-20 at 20 04 53@2x](https://github.com/user-attachments/assets/3c6dad56-247c-4f62-a93d-2f2ee973654a)

**Comment by prathercc** [comment]
Closing this issue, code formatted messages should now be rendered properly, use the monospace font, and support for code highlighting will be included with Version 1.12.4 👍
https://github.com/prathercc/discrub-ext/releases/tag/1.12.14

**Comment by gmile** [comment]
Fantastic, thank you!
