### ISSUE TITLE
Can I use this tool to alert keywords?

### ISSUE THREAD

**Issue by metacopy** [prathercc/discrub-ext#17]
Hi! I wonder if I can use this tool to be alerted when certain keywords appears in chats? Also - can I use it only in my group (owner) or any other group in which I just regular user? Thanks!

**Comment by prathercc** [comment]
With the way this extension works, it won't be possible to be alerted on certain keywords.
However you can use the extension to load Channel/Direct messages and filter for specific keywords manually.

This extension can be used for any Channel or DM that you are apart of 👍
