### ISSUE TITLE
[feature request] search messages in all channels in a guild

### ISSUE THREAD

**Issue by teisseire117** [prathercc/discrub-ext#45]
Hi,

I'm looking to search for a term in a discord server, because discord original search feature doesn't allow for exact term searches. For example searching "localization" will return messages that contains the words "locals", "local" etc and it's unusable.

So I found your tool but apparently we can't search for all channels, and there's a lot of them. I can do it manually but it would be great if there were an option to do it automatically.

thanks

**Comment by prathercc** [comment]
It’s a good idea, I’ll do some research and see what I can do 👍

**Comment by port19x** [comment]
I'll set a 5$ bounty on that

**Comment by prathercc** [comment]
Sorry this took so long, been busy with IRL stuff lol, but just merged some changes that will allow this to happen, see pull request #54 

You should be able to use Advanced Filtering to search by Message Content on a selected Guild, from there you can use the local filters to get an exact term filter on the remaining messages.

This will all be included in version 1.10.10, which has been submitted to the Chrome WebStore, and should be approved and released in the next day or so.

**Comment by port19x** [comment]
> Sorry this took so long, been busy with IRL stuff lol, but just merged some changes that will allow this to happen, see pull request #54
> 
> You should be able to use Advanced Filtering to search by Message Content on a selected Guild (leaving Channel omitted), from there you can use the local filters to get an exact term filter on the remaining messages (from all Channels in that Guild).
> 
> This will all be included in version 1.10.10, which has been submitted to the Chrome WebStore, and should be approved and released in the next day or so.

I'll check it out later today, neat

**Comment by port19x** [comment]
Took a while for me to get around to it, but can verify that it works :+1: 
I'll kofi you the bounty later today.
(let's hope I don't forget again for a week)
