### ISSUE TITLE
Chrome extension not working

### ISSUE THREAD

**Issue by nmeftah** [prathercc/discrub-ext#56]
when i run discrub to scrub a midjourney channel i get errors saying the files arent found

**Comment by prathercc** [comment]
Hey there, are you able to list the steps you followed to encounter this issue? Was this just a Purge on a Guild?
Also any screenshots of the error that you can provide will help as well, if possible

**Comment by nmeftah** [comment]
no actually, it was just a search on a guild and here is a screenshot of the error i recieved 
<img width="745" alt="image" src="https://github.com/prathercc/discrub-ext/assets/137450457/c1066276-d67e-433b-a505-78e7f6420c44">

**Comment by prathercc** [comment]
Those are just warnings that the browser gets while using the Discord web, no need to worry about those as it shouldn't affect the extensions behavior.
