### ISSUE TITLE
@Username showing up as @81083808749724 under 

### ISSUE THREAD

**Issue by DrizzintahL** [prathercc/discrub-ext#58]
![image](https://github.com/prathercc/discrub-ext/assets/139507939/9182d471-38df-4a2b-9de1-437cd3306ab5)

Pic of an example, only filter is the 'date after'

Tried Brave browser and Chrome, server / channel doesn't seem to make a difference.

Basically we're trying to find a tool to count up the amount of mentions of each user in any given week, if anybody knows of an alternative, a lot of people would be very pleased to hear it <3 

Thank you for your time!

**Comment by prathercc** [comment]
This issue will be resolved in Version 1.10.12 (PR #59 ), it's been submitted to the Chrome WebStore and should be available by tomorrow
