### ISSUE TITLE
Searching for has: file or has: image etc results in no messages

### ISSUE THREAD

**Issue by Bruhstander** [prathercc/discrub-ext#62]
![mspaint_nCo0nCg6Tl](https://github.com/prathercc/discrub-ext/assets/95239267/5a2f2128-dfe4-4957-94a8-e423ec156508)

**Comment by prathercc** [comment]
Hey there, 1.10.14 will have a fix for this issue (see PR #63), essentially there will instead be an additional field within Advanced Filtering called Messages Containing, that will contain all of the available types to filter by.

![1](https://github.com/prathercc/discrub-ext/assets/34904535/70ef10c7-9d01-48e8-bb13-3e11c2bd9dc6)
![2](https://github.com/prathercc/discrub-ext/assets/34904535/3fd46d2e-5f53-4825-8304-c5b62c208618)
![3](https://github.com/prathercc/discrub-ext/assets/34904535/71bf6fed-e64f-415d-bb28-519eb81c48eb)

Thanks for posting this issue!
