### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by salmaxon** [prathercc/discrub-ext#65]
This extension was working last week and now gives this error whenever I try to load it while logged in to discord. I have tried restarting browser and computer and re-installing the extension with the same result.

![image](https://github.com/prathercc/discrub-ext/assets/142192670/96d3a534-8cbc-41d1-8f97-3d01f724ac9c)

**Comment by salmaxon** [comment]
![image](https://github.com/prathercc/discrub-ext/assets/142192670/83416449-0bcd-443a-b635-346f7bee78d2)

Still an issue on latest version

**Comment by salmaxon** [comment]
This is the error in the console when bringing up discrub

![image](https://github.com/prathercc/discrub-ext/assets/142192670/a04ad649-3cc8-46f2-8f81-e80b939dd742)

**Comment by PostalPanda** [comment]
Still no resolution here? I am having the same issue on every device.

**Comment by prathercc** [comment]
@PostalPanda @salmaxon Were either you successful on getting this to work? I've dug into this issue but I am unable to determine what the issue could be here unfortunately 😕 
Do you have a script blocker extension running in the background perhaps?

The issue seems to be that the authorization token is unable to be found in the browser when the extension starts, I am wondering if I should add a way to manually enter an authorization token in the case where it could not be found.

**Comment by PostalPanda** [comment]
I was not able to get it working. I ultimately had to figure something else how for the mean time. I will have to check if, perhaps, you need to open a window within discord (Such as a channel or DM) before it will get the authentication token; as the authentication token might not be available until you do. Not sure, I just know when I manually went and obtained the token, I had to open a channel or DM first.

> @PostalPanda @salmaxon Were either you successful on getting this to work? I've dug into this issue but I am unable to determine what the issue could be here unfortunately 😕 Do you have a script blocker extension running in the background perhaps?
> 
> The issue seems to be that the authorization token is unable to be found in the browser when the extension starts, I am wondering if I should add a way to manually enter an authorization token in the case where it could not be found.

**Comment by prathercc** [comment]
> I was not able to get it working. I ultimately had to figure something else how for the mean time. I will have to check if, perhaps, you need to open a window within discord (Such as a channel or DM) before it will get the authentication token; as the authentication token might not be available until you do. Not sure, I just know when I manually went and obtained the token, I had to open a channel or DM first.
> 
> > @PostalPanda @salmaxon Were either you successful on getting this to work? I've dug into this issue but I am unable to determine what the issue could be here unfortunately 😕 Do you have a script blocker extension running in the background perhaps?
> > The issue seems to be that the authorization token is unable to be found in the browser when the extension starts, I am wondering if I should add a way to manually enter an authorization token in the case where it could not be found.

As of 1.11.0 you should be able to manually enter an Authorization token into Discrub, if you encounter this issue - https://imgur.com/a/F9SNzai

Sorry that this issue continues to persist for you 🙁 Hopefully this will be able to help others facing this problem.

**Comment by markhicken** [comment]
For me, it fails in Brave browser and manually entering the token doesn't help. But it works fine in a clean instance of Chrome.
