### ISSUE TITLE
emotes

### ISSUE THREAD

**Issue by foxysocksy** [prathercc/discrub-ext#70]
Is it possible for exports to include emote-reacts?

**Comment by prathercc** [comment]
I'm going to be including this in the next release (Version 1.11.1), shouldn't be too much longer🤞

**Comment by prathercc** [comment]
PR #72 includes Guild Emoji support, which will be apart of Version 1.11.1.
I am however, going to delay the reaction portion for the moment, I need some more time to plan how I want to go about supporting reactions.
I'll update here again, once I do get reactions added.

**Comment by prathercc** [comment]
PR #90 includes support for message reactions, I will be closing this issue but feel free to create another issue for any suggestions or requests.
