### ISSUE TITLE
[Feature Request] Save Embed contents from a bot

### ISSUE THREAD

**Issue by UltraStuff** [prathercc/discrub-ext#76]
Embed text boxes like these don't get read/saved

![image](https://github.com/prathercc/discrub-ext/assets/103267353/24dcb346-4bc1-4782-a13e-e4d27a86f663)

**Comment by prathercc** [comment]
I’m still working on this one but it will definitely be included in the next release 👍

**Comment by prathercc** [comment]
This will be included with Version 1.11.2, which should be available within the next day or so ✅
