### ISSUE TITLE
Names are appearing as discordID

### ISSUE THREAD

**Issue by DrizzintahL** [prathercc/discrub-ext#79]
https://gyazo.com/77ea4f2d5d03b9e9be6a526ad9f1a53e

Just a heads up.  I really appreciate what you do!  This is saving a ton of time for a lot of people xD

Also, any chance we can get an option to revert version?  I'm not too familiar with Github, but I looked around on there and chrome store and can't find it. 

Cheers!

**Comment by DrizzintahL** [comment]
Technically I'm not sure if anything is working incorrectly, but it's definitely different.  A friend of a friend made a tiny executable that counts up all @mentions and tallies each one and now that's outputting the number instead of the name.  

However, I wanted to ask you, if you were interested in making a Discrub setting OR an entirely different extension, I know a TON of servers that would 100% utilize something that could scan an "appreciation" channel and count up the amount of @mentions of each person, and one that could scan a "who I supported" channel, that counts up the amount of tags per poster.  If that makes sense.  Basically there are infinite streamer discords out there and they credit people for watching other streamers, then you come in after your stream and thank whoever showed up; both of those channels need to be tallied and a lot of the ones I've seen, people do that shit manually each week.  If you had a button that worked both ways, I guarantee people would pay for that.  Or if you remain free I'm sure donations would go up. 

Either way, I love what you're doing.  I have no idea how difficult this coding is, but if you were ever curious on the above paragraph I can answer anything about it.  Sooooo many "support" streamer communities discords that would utilize that sort of automation.

**Comment by prathercc** [comment]
> Technically I'm not sure if anything is working incorrectly, but it's definitely different. A friend of a friend made a tiny executable that counts up all @mentions and tallies each one and now that's outputting the number instead of the name.
> 
> However, I wanted to ask you, if you were interested in making a Discrub setting OR an entirely different extension, I know a TON of servers that would 100% utilize something that could scan an "appreciation" channel and count up the amount of @mentions of each person, and one that could scan a "who I supported" channel, that counts up the amount of tags per poster. If that makes sense. Basically there are infinite streamer discords out there and they credit people for watching other streamers, then you come in after your stream and thank whoever showed up; both of those channels need to be tallied and a lot of the ones I've seen, people do that shit manually each week. If you had a button that worked both ways, I guarantee people would pay for that. Or if you remain free I'm sure donations would go up.
> 
> Either way, I love what you're doing. I have no idea how difficult this coding is, but if you were ever curious on the above paragraph I can answer anything about it. Sooooo many "support" streamer communities discords that would utilize that sort of automation.

Hey yes there definitely has been a change in how User mentions are parsed out during exports, I didn’t really think about the impact on JSON exports 😬 
Thanks for bringing this up and I’ll have this fixed in the next day or so 👍

And as far as scanning the “Appreciation” channels, if I understand correctly, you’d just need to be able to obtain a summary of User mentions (along with the amount of times they were mentioned) after a specified date/time? Would you also need to know who created the mention? Also would we only need to account for Users that posted in the “who I supported” channel?

I think I’d want to add something like this as a feature of Discrub and keep it free, would you be able to post some examples of what you would expect to see be outputted?
Eg. Username_1 was mentioned 5 times by User(s): User_2, User_3 and User_4 etc….

**Comment by prathercc** [comment]
@DrizzintahL Alright the User mention JSON issue should be resolved in Version 1.11.4!

Whenever you have a chance, would you be able to provide some examples of the expected output for the "Appreciation", "Who I Supported" channel scanning?

Also I've gone ahead and added the previous releases: https://github.com/prathercc/discrub-ext/releases

If you need to revert to a previous version, you'll need to grab the necessary version from the above link, extract it, enable Developer Mode on `chrome://extensions/` and then click Load Unpacked and select the folder that the files were extracted to.

**Comment by DrizzintahL** [comment]
That's amazing, I really appreciate your response and effort in all this! I'm omw home and I'll post pic and details and examples of the two different queries that I know would be extremely helpful. Eta maybe 30-45 minutes. Thank you so much for hearing me out! If this gets added in I'm going to be spending a lot of time spreading the word xD

**Comment by DrizzintahL** [comment]
Okay, two of the most popular ways streamer support Discords count their supports

Who-I-Supported: https://gyazo.com/24dac6e13b983d5bf9bfb7c046e765b1
This would count the amount of tags for each user that posted in a window (usually a week)
Sepherionx: 3
TheDonnerGman: 3
Jaybebored: 3
MikeVoxel: 3

Etc...  Basically just take that count and export to xls, preferably using Discord Display Name

Second way is Appreciation, or Who-Supported-Me: https://gyazo.com/08f368c63667187301bb0d192f4b3126
This would count how many times someone shows up in other posts, ignoring WHO posted, in a specific channel, in a week time frame, exported to xls (or any format that's easy, but I feel like xls is easy to open to google sheets and available to everybody with a browser.


Both methods should ignore replies, but count being listed multiple times in the same message, as some people keep a personal tally but forget to post for one stream then come in and dump multiple streams worth of names at once.

If this gets added in, in an approachable way I'm definitely spreading the word of this.  Out of all the community streamer support Discords, I only know of one that has some automation, while the rest rely on officers counting manually EVERY WEEK to get these numbers.  Some are only in the hundreds while others are much higher.  I got wind of this, found Discrub, used it to give me a raw file of all messages, then learned a lot about Google Sheets and separating and removing data and automatically tallying mentions and such, but my process was drawn out and hard to explain to people that aren't as savvy as myself, and I'm not savvy enough to put it into a package or code it up.

Either way, thanks for replying to my initial problem and interest in this issue, looking forward to hearing back!  Happy holidays!

**Comment by prathercc** [comment]
> Okay, two of the most popular ways streamer support Discords count their supports
> 
> Who-I-Supported: https://gyazo.com/24dac6e13b983d5bf9bfb7c046e765b1 This would count the amount of tags for each user that posted in a window (usually a week) Sepherionx: 3 TheDonnerGman: 3 Jaybebored: 3 MikeVoxel: 3
> 
> Etc... Basically just take that count and export to xls, preferably using Discord Display Name
> 
> Second way is Appreciation, or Who-Supported-Me: https://gyazo.com/08f368c63667187301bb0d192f4b3126 This would count how many times someone shows up in other posts, ignoring WHO posted, in a specific channel, in a week time frame, exported to xls (or any format that's easy, but I feel like xls is easy to open to google sheets and available to everybody with a browser.
> 
> Both methods should ignore replies, but count being listed multiple times in the same message, as some people keep a personal tally but forget to post for one stream then come in and dump multiple streams worth of names at once.
> 
> If this gets added in, in an approachable way I'm definitely spreading the word of this. Out of all the community streamer support Discords, I only know of one that has some automation, while the rest rely on officers counting manually EVERY WEEK to get these numbers. Some are only in the hundreds while others are much higher. I got wind of this, found Discrub, used it to give me a raw file of all messages, then learned a lot about Google Sheets and separating and removing data and automatically tallying mentions and such, but my process was drawn out and hard to explain to people that aren't as savvy as myself, and I'm not savvy enough to put it into a package or code it up.
> 
> Either way, thanks for replying to my initial problem and interest in this issue, looking forward to hearing back! Happy holidays!

This is definitely something I can do 👍 Thanks again for all of the additional information!

I’ll try to get this added this week, Happy Holidays to you too 🎄!

**Comment by prathercc** [comment]
@DrizzintahL Alright Version 1.11.5 has been submitted and will have the ability to generate Channel tag data spreadsheets!
It should be available in the next day or so via the Chrome store, but can be manually built as well, here is the pre-release: [https://github.com/prathercc/discrub-ext/releases/tag/1.11.5](https://github.com/prathercc/discrub-ext/releases/tag/1.11.5)

Here are some screenshots: [https://imgur.com/a/jl0Kai2](https://imgur.com/a/jl0Kai2)

Basically you'll select the Server and Channel, along with a time period that you wish to collect tag data from.
You can then click Generate Spreadsheet, and select either **Tags Sent By User** or **Tags Received For User**.

**Tags Sent By User** will generate a spreadsheet with every User who tagged another User and the count associated (eg. Who I supported).

**Tags Received For User** will generate a spreadsheet with every User who has been tagged and the amount of times they were tagged (eg. Who supported me).

The name shown for the User is the display name shown in Discord.

Hopefully that makes sense 🤞, please let me know what you think, I'm going to close this issue now, but feel free to create another issue if you'd like to include more data in these spreadsheets, or if you have any other suggestions in general!

**Comment by DrizzintahL** [comment]
This is absolutely insane.  So far so good, looks 100% exactly what we're
looking for.  From initial testing, the count was off by 3, so I *think* it
may be counting replies, as well?  Which isn't a big issue, but I'm still
delving into it, see where the discrepancy is. Either bloody way, going to
be sending some donos your way for this, and spreading the word to other
Discords.  I can't thank you enough!

**Comment by prathercc** [comment]
@DrizzintahL Thanks for the kind words :)
And you're right, I forgot to exclude Message reply tags 🤦

I've added the ability to skip Tags from reply messages (toggled to skip by default) in Version 1.11.6, you can find that pre-release here: [https://github.com/prathercc/discrub-ext/releases/tag/1.11.6](https://github.com/prathercc/discrub-ext/releases/tag/1.11.6)

There was also an issue with Guild nicknames not being shown on the 'Tags Received For User' spreadsheet, this is also resolved in 1.11.6!

I'll have to wait until 1.11.5 is published on the Chrome store before I can submit 1.11.6, but as always, feel free to manually build the pre-release until then!
