### ISSUE TITLE
firefox extension?

### ISSUE THREAD

**Issue by jirafey** [prathercc/discrub-ext#85]

**Comment by jirafey** [comment]
This is still an issue

**Comment by whopastoo** [comment]
> This is still an issue

they deff should add support for firefox

**Comment by jirafey** [comment]
> > This is still an issue
> 
> they deff should add support for firefox

lazy devs will say that it takes long for them to get accepted on the mozilla addons, seems like the project is not abandoned, so no idea what's up @prathercc

**Comment by prathercc** [comment]
> > > This is still an issue
> > 
> > 
> > they deff should add support for firefox
> 
> lazy devs will say that it takes long for them to get accepted on the mozilla addons, seems like the project is not abandoned, so no idea what's up @prathercc

Just created a Mozilla addons account, and used the compatibility tool to see if the extension can be ported over…
It looks like the only issues present are with the icons not being square and the service-worker declaration, and extension id in the manifest file.

![IMG_6818](https://github.com/user-attachments/assets/3e8b914d-47cc-404b-832a-e3588e694774)

In theory I should be able to make the adjustments and it should (🤞) be able to be converted.
I’ll report back here after trying that 👍

**Comment by ajax-lives** [comment]
Hey there, any news?

**Comment by prathercc** [comment]
> Hey there, any news?

Hey there, apologies for the delay, I’m pretty close I think, just trying to work out a few issues with some of the scripts project uses.

I’ve currently got the icon button injecting itself into the page, and the extension can be opened in Firefox etc, but things like auth token parsing and closing out of the extension are not working out of the box and will need some adjustments.

Hoping it won’t take too much longer 🤞

**Comment by ajax-lives** [comment]
Hey man! Thanks for the update and fantastic extension! Good luck and have a lovely one <3

**Comment by prathercc** [comment]
Alright I've got it working pretty well now, here is the official release - https://github.com/prathercc/discrub-ext/releases/tag/1.12.3

I'm going to go ahead and go through the process of adding Discrub to the Firefox store now, but feel free to manually load the addon into Firefox in the meantime.
I'll try to report back here once it's officially available on the Firefox store 🤞

And as always, feel free to give feedback on the Firefox port (if there is anything broken etc...), it should be pretty much identical to the Chrome version.

**Comment by prathercc** [comment]
Here is the link to the Firefox addon: https://addons.mozilla.org/en-US/firefox/addon/discrub/

Everything is approved, going to close this issue now 👌
