### ISSUE TITLE
HTML export not working

### ISSUE THREAD

**Issue by interceptic** [prathercc/discrub-ext#91]
Issue when it tries to compress the page

**Comment by prathercc** [comment]
Hey there, is there any error message in your browsers console?
Also what exactly was being exported, and were you using any of the export options?

**Comment by SamMaybe1** [comment]
TypeError: Cannot destructure property 'guilds' of 'a[y.id]' as it is undefined.
    at main.js:160:12401
    at Array.forEach (<anonymous>)
    at main.js:160:12376
    at main.js:114:45235
    at getFormattedInnerHtml (main.js:168:4908)
    at f (main.js:179:6904)
    at K$ (main.js:179:8832)
    at Ss (chrome-extension://p…c852c03.js:38:19468)
    at ep (chrome-extension://p…c852c03.js:40:43828)
    at Zd (chrome-extension://p…c852c03.js:40:39610)
    
    Many more after that, one being:
GET https://images-ext-2.discordapp.net/external/FZNLcJDKywANBqle33DNGC3VI_yC6n7yoiJg7VT6aJs/%3Fsize%3D1024/https/cdn.discordapp.com/avatars/819898357488025600/67e5b4c698e20603da0bd8ef11c8aee5.png 404 (Not Found)

and another being: chrome-extension://plhdclenpaecffbcefjmpkkbdpkmhhbj/avatars/1198722808054820984/be1ced347aa32e14264bdac8f56ea6a2.png:1 
        
        
       GET chrome-extension://plhdclenpaecffbcefjmpkkbdpkmhhbj/avatars/1198722808054820984/be1ced347aa32e14264bdac8f56ea6a2.png net::ERR_FILE_NOT_FOUND

**Comment by prathercc** [comment]
Gotcha, I see what’s happening and I’ll try to get a fix pushed up tomorrow 👍

**Comment by SamMaybe1** [comment]
Perfect, thank you!

**Comment by interceptic** [comment]
Any luck?

**Comment by prathercc** [comment]
> Any luck?

Yes this should be fixed in Version 1.11.9 which will be officially deployed tonight/early-tomorrow 👍 (depending on how long the Chrome store approval takes).
I'll go ahead and close this issue but please feel free to create another one if something else comes up!

**Comment by prathercc** [comment]
Just an update: sorry for the delay on 1.11.9 being released, it still says pending in the Chrome store, hopefully it won’t be too much longer 🤞
