### ISSUE TITLE
Acendeing and Decending Order | messages exported backwards

### ISSUE THREAD

**Issue by Edfs89i0** [prathercc/discrub-ext#93]
When you export the messages they start from the end and you need to scroll up to see the most recent message rather then scrolling down. There's doesn't seem to be any option to edit this in the setting or filter list.

**Comment by prathercc** [comment]
Hey there, so currently there are two ways that you can change the direction of exported messages:

Option 1 - https://imgur.com/a/MHSKOuU
- Load the messages that you wish to export and click the **Date** column to sort the messages in the desired order, from there you would export the messages as usual and the generated files should use the same sort order.

Option 2 - https://imgur.com/a/qZyBVsb
- If you are bulk exporting messages, there is an export option called **Sort Messages Ascending/Descending** that you can use to export messages newer/older at the top.

Let me know if this helps or if you have any more questions!

**Comment by Ryanqqqq** [comment]
I actually have the same issue no matter what i do the image media won't be in the correct order? (i sent all the blue images first then the yellow).
![image](https://github.com/prathercc/discrub-ext/assets/140095562/4da5f762-acd4-44ea-8f60-4aa46bf3076e)

What im trying to do is have my revision material for my exams offline so im tryna get it in the date order, if you have any fixes that would be awesome

**Comment by prathercc** [comment]
> Not to say this isnt awesome it really is but i do actually have the same issue no matter what i do the image media won't be in the correct order? (i sent all the blue images first then the yellow). I have tried: Exporting it both ways you reccomended In the file ive sorted by every combination
> 
> ![image](https://private-user-images.githubusercontent.com/140095562/313085590-4da5f762-acd4-44ea-8f60-4aa46bf3076e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0ODU3ODYsIm5iZiI6MTcxMDQ4NTQ4NiwicGF0aCI6Ii8xNDAwOTU1NjIvMzEzMDg1NTkwLTRkYTVmNzYyLWFjZDQtNDRlYS04ZjYwLTRhYTQ2YmYzMDc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwNjUxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGU1ZTMzYzM1MmNhOTRjMzIyNmViNjFhZmQyZWEwYWUyYTAwOWFkMjlhNTU3MDY1ZGY4YjQ0YjI2MWIyYjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eh0LdLmUzA5HSlbuZjIQq1cLF5uvYqph26t1GW4hUE0)
> 
> What im trying to do is have my revision material for my exams offline so im tryna get it in the date order, if you have any fixes that would be awesome

Gotcha, I see what you mean 👍
Currently the media itself is not ordered when it’s downloaded (however, if you’re looking for a quick fix then I’d recommend exporting as HTML and viewing the images in the resulting HTML file since the media will be ordered there correctly).
I’ve got Version 1.11.10 releasing soon, I’ll try to include a change that orders media in the same order as the messages would have been.

**Comment by Ryanqqqq** [comment]
Man I really appreciate you bro, the HTML works perfectly thanks man

**Comment by prathercc** [comment]
As of [Version 1.11.10](https://github.com/prathercc/discrub-ext/releases/tag/1.11.10) (should be released in the next day or so), exported media will be ordered in the same direction as their associated messages #96 
Going to go ahead and close this issue, but if anyone notices anything else or has any suggestions, please feel free to open another one!

**Comment by Ryanqqqq** [comment]
My man, dude your an absolute legend, no words can describe my level of gratitude i feel right now. Thanks man i really appreciate you.

**Comment by Ryanqqqq** [comment]
![image](https://github.com/prathercc/discrub-ext/assets/140095562/1fbbfdf6-9e27-4b7f-a824-f981cca775e3)
 works beutifully

**Comment by Matrixx369** [comment]
> Hey there, so currently there are two ways that you can change the direction of exported messages:
> 
> Option 1 - https://imgur.com/a/MHSKOuU
> 
> * Load the messages that you wish to export and click the **Date** column to sort the messages in the desired order, from there you would export the messages as usual and the generated files should use the same sort order.
> 
> Option 2 - https://imgur.com/a/qZyBVsb
> 
> * If you are bulk exporting messages, there is an export option called **Sort Messages Ascending/Descending** that you can use to export messages newer/older at the top.
> 
> Let me know if this helps or if you have any more questions!

Awesome script. Thnanks. 
I don't see  the export options in  option 2 you mentioned above. Has it been removed?
