### ISSUE TITLE
 Allow separating filtered exported messages into folders by what channel they're posted in.

### ISSUE THREAD

**Issue by ghost** [prathercc/discrub-ext#94]
This would be especially ideal when only exporting the messages of a single user ever posted in a guild. Right now, the messages are clumped together in one file, and we have to manually export one channel at a time. This can take a while in larger guilds with dozens of channels.

I am fully aware of the "Export Server" feature. However, this option, as far as I know, does not allow for any filtering other than what channels to be exported.

**Comment by prathercc** [comment]
I can definitely see how this could be an issue, I'll see what can be done here

**Comment by prathercc** [comment]
I'm going to go ahead and close this issue out since Version 1.11.15 will allow Users to use the Advanced Filtering options when exporting entire servers.

This new version should be available in the next day or so, but please feel free to create another issue if something else pops up ✅
