### ISSUE TITLE
The ability to slow down the deletion process

### ISSUE THREAD

**Issue by iansquenet** [prathercc/discrub-ext#97]

**Comment by prathercc** [comment]
I could probably add a new Setting called 'Delete/Action Delay' or similar that accepts a range for the amount of seconds to wait, and the extension could pick a random amount of seconds (based upon what was entered in the new Setting range) and wait that amount of time.
Do you think something like this would be alright? @iansquenet 
Is this slowdown desired for all deletions or only when Discord responds with a rate limitation?

**Comment by iansquenet** [comment]
> Is this slowdown desired for all deletions or only when Discord responds with a rate limitation?
Whichever option works better, I just don't want to fear losing my account. Undiscord does it well, it automatically adds a delay when the rate limit comes. But I find that Discrub allows me to scrub reactions and purge the entire server quite easily.

Some more ideas I had, though I could always open up separate suggestion issue for them:

If it's also possible, then the ability to keep using Discord while the deletion process is happening. Right now the screen is being covered up fully with no ability to click outside of the Discrub box without closing it.

And also queues for servers/DMs (select multiple) so I don't have to purge one by one.

Thank you! 💖

**Comment by prathercc** [comment]
The ability to set Search and Delete/Edit random delay will be included with Version 1.12.0 (it's located within Settings), and I'll see what I can do regarding the minimization of the extension window.
Also this version will include the ability to export and purge multiple DM's, but I'll have to do a bit more work to get Servers setup the same way 🤞
