### ISSUE TITLE
Messages by problem 

### ISSUE THREAD

**Issue by timeg7100** [prathercc/discrub-ext#98]
hi
i have a problem with Messages by
the problem is that i only see me in the list no one else
i don't know if there is any conditions i have to meat for it

thanks

**Comment by prathercc** [comment]
Hey there, so by default only your name will show up on that dropdown (unfortunately Discord does not allow the extension to pull that data without traversing messages first).
As you search Channel messages, other peoples usernames will start populating the dropdown.

You may also paste someone’s userid in the dropdown field if you know it.

I think in the future I’ll will set the extension up to remember the usernames that have been discovered in the past, and still show it for any future sessions to avoid the copy paste stuff.

**Comment by timeg7100** [comment]
hi
i didn't understand the "As you search Channel messages, other peoples usernames will start populating the dropdown."
i think i did what you said but it didn't work
so if you can explain it more for me how to do it i will appreciate it

thanks
