### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by MattVaughan-Jones** [prathercc/discrub-ext#99]
I'm not sure what the problem is, but the extension does nothing when I click on it. It worked fine last week.

**Comment by prathercc** [comment]
I would try reinstalling the extension and seeing if that resolves the issue, let me know if the issue still persists after doing that.
Also I would check if there are any errors in you're browsers console when attempting to open the extension.

**Comment by MattVaughan-Jones** [comment]
Thank you for replying to me, Aaron. I didn't re-install but it seems to be
working again.

Great job on this tool It's extremely useful for me!

**Comment by prathercc** [comment]
Thank you!
